version: '2.1'
 
services:
  contosouniversity.web:
    image: contosouniversity.web:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}    
    volumes:
      - .\ContosoUniversity.Web:C:\inetpub\wwwroot
      - ~\msvsmon:C:\msvsmon:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
 
  contosouniversity.database:
    image: contosouniversity.database:dev
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"